name:                hs-hbpc
version:             0.1.0.0
github:              "ynishi/hs-hbpc"
license:             BSD3
author:              "Yutaka Nishimura"
maintainer:          "ytk.nishimura@gmail.com"
copyright:           "2018 Yutaka Nishimura"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ynishi/hs-hbpc#readme>

dependencies:
- base >= 4.7 && < 5
- lens
- algebraic-graphs
- containers
- stm
- servant-server
- aeson
- text
- wai
- warp
- persistent
- persistent-template
- persistent-mysql
- resourcet
- monad-logger
- transformers
- safe-exceptions
- MissingH
- either

library:
  source-dirs: src

executables:
  hs-hbpc-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-hbpc

tests:
  hs-hbpc-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-hbpc
    - hspec
  hs-hbpc-doctest:
    main:                test/doctest.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-hbpc
    - doctest
